### ISSUE TITLE
include other latex packages

### ISSUE THREAD

**Issue by jmsigner** [jolars/komadown#1]
Is it possible to include other latex packages with `komadown`. The standard way of adding 

```
header-inlcudes:
  - \usepackage{caption}
  - \usepackage{multirow}
```
to the yaml preamble seems to have now effect.

**Comment by jolars** [comment]
You have misspelled includes. It says `header-inlcudes` but should say `header-includes`. Your example works as expected for me after fixing the typo. Please see if that fixes it for you too.

**Comment by jmsigner** [comment]
Well, that is embarrassing. Yes of course it works. Thanks a lot for getting back to me and the package.
