### ISSUE TITLE
Can't specify the keep_tex argument in YAML Header

### ISSUE THREAD

**Issue by Vistagamer** [jolars/komadown#2]
Hi,
i would like to specify a csl file and a template in the YAML Header.
However using Komadown i can't bring it to work. How can i specify this?
My current YAML header is as follows:

```
---
title: "Komadown Versuch"
bibliography: library.bib
output: komadown::scrartcl
template: Scrtemplate.tex
citation-style: kaktus.csl
---
```

would be awesome if someone could help me out. :)

**Comment by jolars** [comment]
By the way, the whole idea with komadown is that it is a special template that wraps around the koma classes. Having your own latex template would defeat its purpose. Also, you need to specify the csl like this:

```
---
output:
  komadown::scrartcl:
    csl: kaktus.csl
---
```

**Comment by Vistagamer** [comment]
Thanks so much for your answer and for the fix! 👍

I just wanted to take your template and modify it in some points. But i think i can do that using the YAML header. Otherwise I'm going to just replace the template.tex.

Thanks again. 👍

**Comment by espinielli** [comment]
Using 
```yaml
...
output:
  komadown::scrartcl:
    keep_tex: yes
...
```
in the `scrartcl` vignette does not kee the intermediate LaTeX.
(I struggled for a couple of hours to see why but it fails me...)

**Comment by jolars** [comment]
Have you tried the development version @espinielli ?

**Comment by espinielli** [comment]
yes.
(in fact I forked your repo to add support for `scrbook` [starting from `scrartcl`] and was trying to compile locally...)
