### ISSUE TITLE
number_sections to FALSE?

### ISSUE THREAD

**Issue by raymondben** [jolars/komadown#3]
Hello - many thanks for a fantastic package, and apologies for what might be a stupid question.
I'd like to remove section numbering, but can't get it to work. I realize that you have set this as a default, but `number_sections: false` in the YAML does not have any effect, nor does `render(myfile, output_format = komadown::scrartcl(number_sections = FALSE))`.
Any suggestions?

**Comment by jolars** [comment]
Thanks, you are right. I noticed this myself but have not gotten around to fixing it just yet.

**Comment by raymondben** [comment]
Ha, no worries. A fix when you have time would be good but no rush from me. Thanks

**Comment by raymondben** [comment]
Belated thanks!
